version: "3"
services:

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:2
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - /volume1/docker/mosquitto:/mosquitto
    user: root
    restart: always
    logging:
      driver: loki
      options:
        loki-url: "http://diskstation:3100/loki/api/v1/push"
  
  nodered:
    container_name: nodered
    image: nodered/node-red:latest
    ports:
      - 1880:1880
      - 2055:2055
      - 2056:2056
    volumes:
      - /volume1/docker/nodered:/data
    user: root
    restart: always
    logging:
      driver: loki
      options:
        loki-url: "http://diskstation:3100/loki/api/v1/push"
