version: "3"
services:

  influxdb:
    container_name: bitwarden
    image: vaultwarden/server
    ports:
      - 3012:3012
      - 5151:80
    volumes:
      - /volume1/docker/bitwarden:/data
    user: root
    restart: always
    logging:
      driver: loki
      options:
        loki-url: "http://diskstation:3100/loki/api/v1/push"
