version: "3"
services:

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:2
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - /volume1/docker/mosquitto:/mosquitto
    user: root
    restart: always
    logging:
      driver: loki
      options:
        loki-url: "http://diskstation:3100/loki/api/v1/push"

  traefik:
    image: "traefik:v2.8"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "88:80"
      - "8088:8080"
    volumes:
      - /volume1/docker/traefik/config:/etc/traefik
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    logging:
      driver: loki
      options:
        loki-url: "http://diskstation:3100/loki/api/v1/push"
  
  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    depends_on: 
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
      - "traefik.http.routers.whoami.entrypoints=web"
    logging:
      driver: loki
      options:
        loki-url: "http://diskstation:3100/loki/api/v1/push"

 

#  mysql:
#    container_name: mysql
#    image: mysql:5
#    ports:
#      - 6603:3306
#    environment:
#      MYSQL_ROOT_PASSWORD: "mypassword"
#    volumes:
#      - /volume1/docker/mysql:/var/lib/mysql
#    networks:
#      - monitoring