version: "3"
services:

  influxdb:
    container_name: influxdb
    image: influxdb:2.4.0
    ports:
      - 8086:8086
    volumes:
      - /volume1/docker/influxdb/data:/var/lib/influxdb2
    user: root
    restart: always
    logging:
      driver: loki
      options:
        loki-url: "http://diskstation:3100/loki/api/v1/push"

  grafana:
    container_name: grafana
    image: grafana/grafana-oss:latest
    ports:
      - 3000:3000
    volumes:
      - /volume1/docker/grafana/config:/etc/grafana
      - /volume1/docker/grafana/data:/var/lib/grafana
    user: root
    restart: always
    logging:
      driver: loki
      options:
        loki-url: "http://diskstation:3100/loki/api/v1/push"

#  mysql:
#    container_name: mysql
#    image: mysql:5
#    ports:
#      - 6603:3306
#    environment:
#      MYSQL_ROOT_PASSWORD: "mypassword"
#    volumes:
#      - /volume1/docker/mysql:/var/lib/mysql
#    networks:
#      - monitoring

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:2
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - /volume1/docker/mosquitto:/mosquitto
    user: root
    restart: always

networks:
  backend:
    internal: true
  monitoring:
    driver: bridge