version: "3"
services:

  mysql:
    image: mysql:5
    container_name: mysql
    ports:
      - 6603:3306
    environment:
      MYSQL_ROOT_PASSWORD: "mypassword"
    volumes:
      - /volume1/docker/mysql:/var/lib/mysql
    networks:
      - monitoring

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:2
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - /volume1/docker/mosquitto:/mosquitto
    user: root
    restart: always

networks:
  backend:
    internal: true
  monitoring:
    driver: bridge