version: "3"
services:

  mysql:
    image: mysql:5
    container_name: mysql
    ports:
      - 6603:3306
    environment:
      MYSQL_ROOT_PASSWORD: "mypassword"
    volumes:
      - /volume1/docker/mysql:/var/lib/mysql
    networks:
      - monitoring

networks:
  backend:
    internal: true
  monitoring:
    driver: bridge